import { CaseItem, AuditLogEntry, AnalyticsData } from '../types';

export const INITIAL_CASES: CaseItem[] = [
  {
    id: 'CF-1024',
    title: 'Apex Global Logistics vs. Metro Infra Ltd',
    caseType: 'Civil Commercial Dispute',
    court: 'District Civil Court — Division 3 (Fictional)',
    filedDate: '14 Feb 2025',
    currentStage: 'Discovery / Evidence',
    lastActivityDate: '15 Jul 2026',
    daysInactive: 94,
    priority: 'HIGH',
    status: 'Bottleneck Detected',
    parties: [
      { name: 'Apex Global Logistics Pvt Ltd', role: 'Plaintiff', counsel: 'Adv. R. V. Sharma', status: 'Complied' },
      { name: 'Metro Infrastructure Ltd', role: 'Defendant', counsel: 'Adv. K. S. Nair', status: 'Non-responsive' },
    ],
    facts: [
      { id: 'f1', field: 'Case Identifier', value: 'CF-1024', type: 'CONFIRMED FACT', confidence: 0.99, sourceDocument: 'Petition_CF1024.pdf' },
      { id: 'f2', field: 'Filing Date', value: '14 Feb 2025', type: 'CONFIRMED FACT', confidence: 0.98, sourceDocument: 'Petition_CF1024.pdf' },
      { id: 'f3', field: 'Court Order Direction', value: 'Parties directed to submit documentary proof within 30 days', type: 'CONFIRMED FACT', confidence: 0.96, sourceDocument: 'Court_Order_12_June_2026.pdf' },
      { id: 'f4', field: 'Party A Submission', value: 'Financial audit records submitted on 15 Jul 2026', type: 'CONFIRMED FACT', confidence: 0.95, sourceDocument: 'PartyA_Evidence_15Jul.pdf' },
      { id: 'f5', field: 'Party B Submission Status', value: 'No corresponding evidence recorded from Metro Infra Ltd in court registry', type: 'AI INFERENCE', confidence: 0.87, sourceDocument: 'Court_Registry_Log.pdf' },
      { id: 'f6', field: 'Subsequent Filings', value: 'No post-July filings recorded in registry', type: 'UNKNOWN', confidence: 0.5 },
    ],
    documents: [
      {
        id: 'doc-101',
        fileName: 'Petition_CF1024.pdf',
        fileType: 'PDF',
        uploadedAt: '14 Feb 2025',
        fileSize: '2.4 MB',
        status: 'Processed',
        documentType: 'Petition',
        summary: 'Original petition for breach of contract and recovery of liquidated damages in logistics operations.',
      },
      {
        id: 'doc-102',
        fileName: 'Court_Order_12_June_2026.pdf',
        fileType: 'PDF',
        uploadedAt: '12 Jun 2026',
        fileSize: '840 KB',
        status: 'Processed',
        documentType: 'Court Order',
        summary: 'Interlocutory order directing both parties to exchange audited freight receipts by 15 July 2026.',
      },
      {
        id: 'doc-103',
        fileName: 'PartyA_Evidence_15Jul.pdf',
        fileType: 'PDF',
        uploadedAt: '15 Jul 2026',
        fileSize: '4.1 MB',
        status: 'Processed',
        documentType: 'Evidence Submission',
        summary: 'Freight manifest receipts and bank transfer slips submitted by Plaintiff Apex Global.',
      },
    ],
    timeline: [
      { id: 't1', date: '14 Feb 2025', eventType: 'Case Filed', description: 'Civil Suit CF-1024 instituted by Apex Global Logistics.', sourceDocument: 'Petition_CF1024.pdf', confidence: 0.99 },
      { id: 't2', date: '14 Mar 2025', eventType: 'Response Submitted', description: 'Written Statement filed by Metro Infra Ltd disputing invoice calculations.', sourceDocument: 'Written_Statement.pdf', confidence: 0.95 },
      { id: 't3', date: '25 May 2026', eventType: 'Hearing Held', description: 'Framing of issues completed; discovery schedule established.', sourceDocument: 'Hearing_Minutes_May25.pdf', confidence: 0.92 },
      { id: 't4', date: '12 Jun 2026', eventType: 'Court Order Issued', description: 'Court order directing mandatory exchange of documentary evidence by 15 Jul 2026.', sourceDocument: 'Court_Order_12_June_2026.pdf', confidence: 0.98 },
      { id: 't5', date: '15 Jul 2026', eventType: 'Evidence Submitted', description: 'Party A (Apex) submitted certified audit records.', sourceDocument: 'PartyA_Evidence_15Jul.pdf', confidence: 0.96 },
      { id: 't6', date: '18 Sep 2026', eventType: 'Deadline Passed', description: 'No Party B (Metro Infra) evidence submission recorded in case repository.', sourceDocument: 'Court Registry Status', confidence: 0.87 },
    ],
    bottlenecks: [
      {
        id: 'bot-1024',
        caseId: 'CF-1024',
        type: 'Missing Document',
        severity: 'HIGH',
        description: 'No evidence submission recorded from Defendant (Metro Infra Ltd) following the court order dated 12 June 2026.',
        detectedDate: '18 Sep 2026',
        durationDays: 94,
        supportingEvidence: [
          'Court Order dated 12 June 2026 directed mutual evidence filing by 15 July 2026.',
          'Party A evidence submission received on 15 July 2026.',
          'No corresponding Party B submission exists in the provided record repository.',
        ],
        confidence: 0.87,
        potentialImpact: 'Case cannot proceed to pre-trial motion or oral testimony until Defendant evidence is received or waived.',
        suggestedInvestigation: 'Issue administrative notice requiring Defendant to submit missing evidence or explain non-compliance.',
        dependencyNodes: [
          { id: 'n1', label: 'Court Order (12 June)', status: 'completed', detail: 'Mandated evidence exchange' },
          { id: 'n2', label: 'Party A Evidence', status: 'completed', detail: 'Submitted 15 July 2026' },
          { id: 'n3', label: 'Party B Evidence', status: 'missing', detail: 'No filing recorded' },
          { id: 'n4', label: 'Pre-Trial Hearing', status: 'blocked', detail: 'Waiting on evidence closure' },
        ],
        isResolved: false,
      },
    ],
    actions: [
      {
        id: 'act-1024',
        caseId: 'CF-1024',
        actionType: 'Request Missing Evidence',
        reason: 'The provided case records indicate that evidence was requested on 12 June 2026 and no corresponding submission from Party B (Metro Infra Ltd) is present.',
        supportingEvidence: ['Court Order — 12 June 2026', 'Registry Filing Log — 15 July 2026'],
        priority: 'HIGH',
        affectedElement: 'Discovery / Evidence Stage',
        draftCommunication: 'FORMAL ADMINISTRATIVE NOTICE:\n\nTo: Counsel for Defendant (Metro Infrastructure Ltd)\nRe: Civil Suit CF-1024 - Non-compliance with Order dated 12 June 2026\n\nPlease take notice that as per Court Order dated 12 June 2026, documentary evidence was due by 15 July 2026. While Plaintiff filings were recorded on 15 July, no Defendant submission appears on record. Please file the missing documents within 7 working days or submit formal grounds for extension.',
        confidence: 0.87,
        status: 'Pending Approval',
        createdAt: '18 Sep 2026 10:34',
      },
    ],
  },
  {
    id: 'CF-1087',
    title: 'Vanguard Tech Solutions vs. Horizon Realty',
    caseType: 'Commercial Arbitration Appeal',
    court: 'High Court Commercial Bench — Division 1',
    filedDate: '03 Dec 2024',
    currentStage: 'Pleadings',
    lastActivityDate: '20 Aug 2026',
    daysInactive: 48,
    priority: 'MEDIUM',
    status: 'Awaiting Response',
    parties: [
      { name: 'Vanguard Tech Solutions', role: 'Petitioner', counsel: 'Adv. M. Mehta', status: 'Complied' },
      { name: 'Horizon Realty Pvt Ltd', role: 'Respondent', counsel: 'Adv. S. K. Gupta', status: 'Non-responsive' },
    ],
    facts: [
      { id: 'f87-1', field: 'Case Identifier', value: 'CF-1087', type: 'CONFIRMED FACT', confidence: 0.99, sourceDocument: 'Petition_CF1087.pdf' },
      { id: 'f87-2', field: 'Notice Served', value: 'Notice delivered on 20 Aug 2026', type: 'CONFIRMED FACT', confidence: 0.94, sourceDocument: 'Service_Ack_20Aug.pdf' },
      { id: 'f87-3', field: 'Counter-Affidavit', value: 'Counter-affidavit due within 30 days of service', type: 'AI INFERENCE', confidence: 0.91, sourceDocument: 'Procedural_Rules_Sec4.pdf' },
    ],
    documents: [
      {
        id: 'doc-1087-1',
        fileName: 'Arbitration_Notice_Aug20.pdf',
        fileType: 'PDF',
        uploadedAt: '20 Aug 2026',
        fileSize: '1.2 MB',
        status: 'Processed',
        documentType: 'Notice',
        summary: 'Official notice issued to Respondent to file counter-affidavit within 30 days.',
      },
    ],
    timeline: [
      { id: 't87-1', date: '03 Dec 2024', eventType: 'Case Filed', description: 'Arbitration appeal filed.', sourceDocument: 'Petition_CF1087.pdf', confidence: 0.99 },
      { id: 't87-2', date: '20 Aug 2026', eventType: 'Court Order Issued', description: 'Notice served to Respondent.', sourceDocument: 'Service_Ack_20Aug.pdf', confidence: 0.94 },
    ],
    bottlenecks: [
      {
        id: 'bot-1087',
        caseId: 'CF-1087',
        type: 'Pending Response',
        severity: 'MEDIUM',
        description: 'Respondent has not filed counter-affidavit after 48 days (statutory deadline: 30 days).',
        detectedDate: '20 Sep 2026',
        durationDays: 48,
        supportingEvidence: ['Service acknowledgment dated 20 Aug 2026.'],
        confidence: 0.91,
        potentialImpact: 'Case pleadings remain unclosed.',
        suggestedInvestigation: 'Issue formal deadline reminder notice to Respondent counsel.',
        dependencyNodes: [
          { id: 'n87-1', label: 'Notice Served (20 Aug)', status: 'completed' },
          { id: 'n87-2', label: 'Counter-Affidavit', status: 'missing', detail: 'Overdue by 18 days' },
        ],
        isResolved: false,
      },
    ],
    actions: [
      {
        id: 'act-1087',
        caseId: 'CF-1087',
        actionType: 'Prepare Pending-Response Follow-up',
        reason: 'Respondent has exceeded the 30-day statutory response window following notice delivery.',
        supportingEvidence: ['Notice Delivery Receipt 20 Aug 2026'],
        priority: 'MEDIUM',
        affectedElement: 'Pleadings Stage',
        draftCommunication: 'REMINDER NOTICE:\n\nTo: Counsel for Respondent (Horizon Realty)\nRe: Commercial Appeal CF-1087\n\nNotice was served on 20 Aug 2026. The 30-day counter-affidavit window expired on 19 Sep 2026. Please file response immediately.',
        confidence: 0.91,
        status: 'Pending Approval',
        createdAt: '21 Sep 2026 09:15',
      },
    ],
  },
  {
    id: 'CF-1112',
    title: 'State Mutual Bank vs. Zenith Engineering',
    caseType: 'Civil Recovery Suit',
    court: 'Debt Recovery Tribunal — Bench II',
    filedDate: '10 Jan 2024',
    currentStage: 'Hearing',
    lastActivityDate: '01 Jun 2026',
    daysInactive: 128,
    priority: 'CRITICAL',
    status: 'Requires Attention',
    parties: [
      { name: 'State Mutual Bank', role: 'Plaintiff', counsel: 'Adv. T. Sengupta', status: 'Complied' },
      { name: 'Zenith Engineering Corp', role: 'Defendant', counsel: 'Adv. D. P. Roy', status: 'Active' },
    ],
    facts: [
      { id: 'f112-1', field: 'Adjournment Count', value: '4 consecutive hearing adjournments granted', type: 'CONFIRMED FACT', confidence: 0.97, sourceDocument: 'Hearing_Log_2026.pdf' },
      { id: 'f112-2', field: 'Reason for Adjournments', value: 'Counsel unavailable / sickness certificate filed', type: 'CONFIRMED FACT', confidence: 0.92, sourceDocument: 'Adjournment_Applications.pdf' },
    ],
    documents: [
      {
        id: 'doc-1112-1',
        fileName: 'Hearing_Log_2026.pdf',
        fileType: 'PDF',
        uploadedAt: '01 Jun 2026',
        fileSize: '1.8 MB',
        status: 'Processed',
        documentType: 'Court Order',
        summary: 'Log of hearings showing repeated adjournments requested by Defendant counsel.',
      },
    ],
    timeline: [
      { id: 't112-1', date: '10 Jan 2024', eventType: 'Case Filed', description: 'Recovery suit instituted.', sourceDocument: 'Petition_CF1112.pdf', confidence: 0.99 },
      { id: 't112-2', date: '15 Feb 2026', eventType: 'Hearing Held', description: 'Adjourned at Defendant request.', sourceDocument: 'Hearing_Log_2026.pdf', confidence: 0.95 },
      { id: 't112-3', date: '20 Apr 2026', eventType: 'Hearing Held', description: 'Adjourned at Defendant request.', sourceDocument: 'Hearing_Log_2026.pdf', confidence: 0.95 },
      { id: 't112-4', date: '01 Jun 2026', eventType: 'Hearing Held', description: 'Adjourned for final arguments without fixed next date.', sourceDocument: 'Hearing_Log_2026.pdf', confidence: 0.95 },
    ],
    bottlenecks: [
      {
        id: 'bot-1112',
        caseId: 'CF-1112',
        type: 'Repeated Adjournment',
        severity: 'CRITICAL',
        description: 'Case has suffered 4 consecutive adjournments with over 120 days of inactivity since last hearing.',
        detectedDate: '15 Sep 2026',
        durationDays: 128,
        supportingEvidence: ['Hearing minutes dated 15 Feb, 20 Apr, 01 Jun 2026.'],
        confidence: 0.95,
        potentialImpact: 'Risk of procedural dismissal or excessive delay in recovery process.',
        suggestedInvestigation: 'Prepare hearing brief and request expedited hearing date assignment.',
        dependencyNodes: [
          { id: 'n112-1', label: 'Adjournment #1', status: 'completed' },
          { id: 'n112-2', label: 'Adjournment #2', status: 'completed' },
          { id: 'n112-3', label: 'Adjournment #3', status: 'completed' },
          { id: 'n112-4', label: 'Hearing Listing', status: 'blocked', detail: 'No next date fixed' },
        ],
        isResolved: false,
      },
    ],
    actions: [
      {
        id: 'act-1112',
        caseId: 'CF-1112',
        actionType: 'Prepare Hearing Brief',
        reason: 'Prolonged inactivity following repeated adjournments without a scheduled next date.',
        supportingEvidence: ['Hearing Log 01 Jun 2026'],
        priority: 'CRITICAL',
        affectedElement: 'Hearing Stage',
        draftCommunication: 'EXPEDITED LISTING APPLICATION:\n\nTo: Registrar, DRT Bench II\nRe: Suit CF-1112\n\nPraying for early fixed hearing date as matter has remained adjourned since 01 June 2026.',
        confidence: 0.94,
        status: 'Pending Approval',
        createdAt: '16 Sep 2026 14:20',
      },
    ],
  },
  {
    id: 'CF-1190',
    title: 'Clean Energy Developers vs. Municipal Corp',
    caseType: 'Administrative Compliance Review',
    court: 'Administrative Appellate Board',
    filedDate: '05 May 2025',
    currentStage: 'Pre-Trial Motion',
    lastActivityDate: '25 Sep 2026',
    daysInactive: 12,
    priority: 'HIGH',
    status: 'Requires Attention',
    upcomingDeadline: '12 Oct 2026',
    parties: [
      { name: 'Clean Energy Developers Ltd', role: 'Petitioner', counsel: 'Adv. A. Kapoor', status: 'Active' },
      { name: 'Municipal Corporation', role: 'Respondent', counsel: 'Adv. S. Verma', status: 'Active' },
    ],
    facts: [
      { id: 'f1190-1', field: 'Compliance Filing Deadline', value: '12 Oct 2026 statutory deadline', type: 'CONFIRMED FACT', confidence: 0.99, sourceDocument: 'Board_Direction_Sep25.pdf' },
    ],
    documents: [
      {
        id: 'doc-1190-1',
        fileName: 'Board_Direction_Sep25.pdf',
        fileType: 'PDF',
        uploadedAt: '25 Sep 2026',
        fileSize: '950 KB',
        status: 'Processed',
        documentType: 'Court Order',
        summary: 'Board order setting deadline of 12 Oct 2026 for environmental assessment report.',
      },
    ],
    timeline: [
      { id: 't1190-1', date: '05 May 2025', eventType: 'Case Filed', description: 'Compliance review petition filed.', sourceDocument: 'Petition_CF1190.pdf', confidence: 0.99 },
      { id: 't1190-2', date: '25 Sep 2026', eventType: 'Court Order Issued', description: 'Direction issued setting 12 Oct compliance deadline.', sourceDocument: 'Board_Direction_Sep25.pdf', confidence: 0.98 },
    ],
    bottlenecks: [
      {
        id: 'bot-1190',
        caseId: 'CF-1190',
        type: 'Upcoming Deadline',
        severity: 'HIGH',
        description: 'Mandatory environmental compliance report due on 12 Oct 2026 (5 days remaining).',
        detectedDate: '01 Oct 2026',
        durationDays: 12,
        supportingEvidence: ['Board Direction dated 25 Sep 2026.'],
        confidence: 0.98,
        potentialImpact: 'Failure to submit will incur administrative penalties and stay on project.',
        suggestedInvestigation: 'Highlight upcoming deadline to case management team.',
        dependencyNodes: [
          { id: 'n1190-1', label: 'Order Issued (25 Sep)', status: 'completed' },
          { id: 'n1190-2', label: 'Report Submission', status: 'pending', detail: 'Due 12 Oct 2026' },
        ],
        isResolved: false,
      },
    ],
    actions: [
      {
        id: 'act-1190',
        caseId: 'CF-1190',
        actionType: 'Highlight Deadline',
        reason: 'Statutory compliance deadline approaching within 5 calendar days.',
        supportingEvidence: ['Board Order 25 Sep 2026'],
        priority: 'HIGH',
        affectedElement: 'Pre-Trial Motion Stage',
        draftCommunication: 'URGENT DEADLINE ALERT:\n\nTo: Lead Administrative Officer\nRe: Case CF-1190\n\nPlease ensure Environmental Impact Assessment report is lodged prior to 12 Oct 2026 deadline.',
        confidence: 0.98,
        status: 'Pending Approval',
        createdAt: '01 Oct 2026 11:00',
      },
    ],
  },
  {
    id: 'CF-1214',
    title: 'Heritage Trust vs. Urban Development Authority',
    caseType: 'Civil Property Suit',
    court: 'District Civil Court — Division 1',
    filedDate: '12 Jan 2026',
    currentStage: 'Pleadings',
    lastActivityDate: '02 Oct 2026',
    daysInactive: 5,
    priority: 'LOW',
    status: 'Active',
    parties: [
      { name: 'Heritage Conservation Trust', role: 'Plaintiff', counsel: 'Adv. P. N. Swamy', status: 'Active' },
      { name: 'Urban Development Authority', role: 'Defendant', counsel: 'Adv. G. Rao', status: 'Active' },
    ],
    facts: [
      { id: 'f1214-1', field: 'Pleading Status', value: 'Written statement filed on time on 02 Oct 2026', type: 'CONFIRMED FACT', confidence: 0.98, sourceDocument: 'WS_02Oct2026.pdf' },
    ],
    documents: [
      {
        id: 'doc-1214-1',
        fileName: 'WS_02Oct2026.pdf',
        fileType: 'PDF',
        uploadedAt: '02 Oct 2026',
        fileSize: '1.5 MB',
        status: 'Processed',
        documentType: 'Petition',
        summary: 'Defendant written statement lodged within statutory period.',
      },
    ],
    timeline: [
      { id: 't1214-1', date: '12 Jan 2026', eventType: 'Case Filed', description: 'Suit filed.', sourceDocument: 'Petition.pdf', confidence: 0.99 },
      { id: 't1214-2', date: '02 Oct 2026', eventType: 'Response Submitted', description: 'Defendant filed Written Statement.', sourceDocument: 'WS_02Oct2026.pdf', confidence: 0.98 },
    ],
    bottlenecks: [],
    actions: [],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-1',
    timestamp: '18 Sep 2026 10:32',
    userOrAgent: 'CaseUnderstandingAgent',
    caseId: 'CF-1024',
    agentRole: 'CaseUnderstandingAgent',
    action: 'Document Analysis',
    inputReference: 'PartyA_Evidence_15Jul.pdf',
    outputDetails: 'Extracted key dates, parties, and court orders.',
    status: 'Completed',
  },
  {
    id: 'aud-2',
    timestamp: '18 Sep 2026 10:33',
    userOrAgent: 'BottleneckAgent',
    caseId: 'CF-1024',
    agentRole: 'BottleneckAgent',
    action: 'Bottleneck Detection',
    inputReference: 'Structured Case JSON CF-1024',
    outputDetails: 'Identified Missing Document bottleneck with 87% confidence.',
    status: 'Completed',
  },
  {
    id: 'aud-3',
    timestamp: '18 Sep 2026 10:34',
    userOrAgent: 'ActionAgent',
    caseId: 'CF-1024',
    agentRole: 'ActionAgent',
    action: 'Action Recommendation',
    inputReference: 'Bottleneck bot-1024',
    outputDetails: 'Prepared recommended action: Request Missing Evidence.',
    status: 'Pending Review',
  },
  {
    id: 'aud-4',
    timestamp: '20 Sep 2026 14:10',
    userOrAgent: 'BottleneckAgent',
    caseId: 'CF-1087',
    agentRole: 'BottleneckAgent',
    action: 'Bottleneck Detection',
    inputReference: 'Structured Case JSON CF-1087',
    outputDetails: 'Identified Pending Response bottleneck after 48 days inactivity.',
    status: 'Completed',
  },
];

export const INITIAL_ANALYTICS: AnalyticsData = {
  totalCases: 1250,
  requiresAttention: 24,
  highPriority: 18,
  bottlenecksDetected: 438,
  actionsAwaitingApproval: 8,
  actionsCompleted: 312,
  potentiallyUnblocked: 137,
  upcomingDeadlines: 14,
  prolongedInactivityCount: 89,
  avgDetectionToActionDays: 2.4,
  avgActionToResolutionDays: 6.8,
};
